name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        # Obtén el secreto y configúralo como una variable global de JavaScript
        echo "window.GITHUB_API_KEY='${{ secrets.API_KEY }}';" > secrets.js

        # Lanza tu proceso de compilación y despliegue aquí
        npm install
        npm run build

        # Copia los archivos generados (por ejemplo, en la carpeta "dist") a la carpeta adecuada para GitHub Pages
        cp -r dist/* docs/
      env:
        API_KEY: ${{ secrets.API_KEY }}

